### ISSUE TITLE
method has no signature when trying to remove globals from hpo (hyperopt)

### ISSUE THREAD

**Issue by krajasethupathy** [gilt/odsc-2018#4]
on branch: https://github.com/gilt/odsc-2018/tree/add_hyperopt

to run: `PYTHONPATH=. python hpo/hyperopt_hpo.py 5 127.0.0.1:27017 sacred`

stack trace:
```
Traceback (most recent call last):
  File "hpo/hyperopt_hpo.py", line 152, in <module>
    trial_results, best = hyperopt_exps.run_hyperopt()
  File "hpo/hyperopt_hpo.py", line 89, in run_hyperopt
    trials=trials)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/fmin.py", line 307, in fmin
    return_argmin=return_argmin,
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/base.py", line 635, in fmin
    return_argmin=return_argmin)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/fmin.py", line 320, in fmin
    rval.exhaust()
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/fmin.py", line 199, in exhaust
    self.run(self.max_evals - n_done, block_until_done=self.async)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/fmin.py", line 173, in run
    self.serial_evaluate()
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/fmin.py", line 92, in serial_evaluate
    result = self.domain.evaluate(spec, ctrl)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/hyperopt/base.py", line 840, in evaluate
    rval = self.fn(pyll_rval)
  File "hpo/hyperopt_hpo.py", line 47, in objective
    self.hyperopt_exp.main(self.run_base_experiment)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/sacred/experiment.py", line 97, in main
    captured = self.command(function)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/sacred/utils.py", line 298, in optional_kwargs_decorator
    return wrapped(*args, **kwargs)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/sacred/ingredient.py", line 123, in command
    captured_f = self.capture(function, prefix=prefix)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/sacred/utils.py", line 298, in optional_kwargs_decorator
    return wrapped(*args, **kwargs)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/sacred/ingredient.py", line 79, in capture
    captured_function = create_captured_function(function, prefix=prefix)
  File "/web/odsc-2018/sacred-demo/lib/python3.6/site-packages/sacred/config/captured_function.py", line 18, in create_captured_function
    function.signature = sig
AttributeError: 'method' object has no attribute 'signature'
```

**Comment by krajasethupathy** [comment]
@JasonTam error above. Below is the line that leads to the issue... showing how its run before and after i made changes to remove the globals.

**This works:**
version with globals: https://github.com/gilt/odsc-2018/blob/add_hyperopt/experiments/hyperopt_experiment.py#L34

**This doesn't work**
version without globals: https://github.com/gilt/odsc-2018/blob/add_hyperopt/hpo/hyperopt_hpo.py#L49
